const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349133966402";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_39_09_02_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAyNDcsXG4gICAgICAgIDM0LFxuICAgICAgICA3LFxuICAgICAgICAxMTAsXG4gICAgICAgIDI5LFxuICAgICAgICAxNDgsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTM4LFxuICAgICAgICA2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE2NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNjgsXG4gICAgICAgIDEzLFxuICAgICAgICAxNjIsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjA1LFxuICAgICAgICAxODEsXG4gICAgICAgIDY2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDgyLFxuICAgICAgICAzMyxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNzksXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjQwLFxuICAgICAgICAyNyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjMzLFxuICAgICAgICAyNTEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDEsXG4gICAgICAgIDEwNCxcbiAgICAgICAgNzUsXG4gICAgICAgIDE4OCxcbiAgICAgICAgNDMsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTg0LFxuICAgICAgICAzMSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxOTYsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNzQsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjIxLFxuICAgICAgICAxNDksXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDk1LFxuICAgICAgICA1MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNDQsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMzAsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMjJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDgwLFxuICAgICAgICA0NSxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNjksXG4gICAgICAgIDI0MixcbiAgICAgICAgMTg4LFxuICAgICAgICAxMTQsXG4gICAgICAgIDMzLFxuICAgICAgICAxNzEsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIxMixcbiAgICAgICAgNzgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNyxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMTUsXG4gICAgICAgIDk4LFxuICAgICAgICAxMzYsXG4gICAgICAgIDMyLFxuICAgICAgICAxNjksXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTQ2LFxuICAgICAgICA0OSxcbiAgICAgICAgMTMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjUzLFxuICAgICAgICA1OSxcbiAgICAgICAgMTI0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExMyxcbiAgICAgICAgOTQsXG4gICAgICAgIDg0LFxuICAgICAgICAyNixcbiAgICAgICAgMTMsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNDMsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTcwLFxuICAgICAgICAxMTMsXG4gICAgICAgIDI3LFxuICAgICAgICAxMDksXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTEyLFxuICAgICAgICAzMixcbiAgICAgICAgMjUzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDI0NSxcbiAgICAgICAgNDcsXG4gICAgICAgIDE1LFxuICAgICAgICA4NSxcbiAgICAgICAgMjQsXG4gICAgICAgIDY1LFxuICAgICAgICAyNCxcbiAgICAgICAgMTc2LFxuICAgICAgICAyMDQsXG4gICAgICAgIDgsXG4gICAgICAgIDUyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDU4LFxuICAgICAgICA5MixcbiAgICAgICAgNDJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTg5LFxuICAgICAgICA5MCxcbiAgICAgICAgMTM5LFxuICAgICAgICAyMDIsXG4gICAgICAgIDI0MixcbiAgICAgICAgNjUsXG4gICAgICAgIDEyLFxuICAgICAgICAxMjQsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTkyLFxuICAgICAgICAyMjYsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTM1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTQ5LFxuICAgICAgICA5MixcbiAgICAgICAgMjEyLFxuICAgICAgICAyMTQsXG4gICAgICAgIDI4LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIwLFxuICAgICAgICAxMzAsXG4gICAgICAgIDI1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTYzLFxuICAgICAgICAxODAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTksXG4gICAgICAgIDEwM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDMwLFxuICAgICAgICA2NyxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNzYsXG4gICAgICAgIDMsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMzIsXG4gICAgICAgIDE0MixcbiAgICAgICAgNjYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgOSxcbiAgICAgICAgMjE0LFxuICAgICAgICA1MyxcbiAgICAgICAgNzYsXG4gICAgICAgIDQ3LFxuICAgICAgICAzOCxcbiAgICAgICAgMTg1LFxuICAgICAgICA5OSxcbiAgICAgICAgNTUsXG4gICAgICAgIDEyMCxcbiAgICAgICAgOTYsXG4gICAgICAgIDMzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyNTEsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMDdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDcxXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAzMCxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDY5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMSxcbiAgICAgICAgMTc0LFxuICAgICAgICAyNDksXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNjEsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTIzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDUzLFxuICAgICAgICAxMjMsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTIsXG4gICAgICAgIDU3LFxuICAgICAgICAxNjYsXG4gICAgICAgIDMxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMTQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMzUsXG4gICAgICAgIDYsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjE0LFxuICAgICAgICAyNyxcbiAgICAgICAgNzksXG4gICAgICAgIDE0MixcbiAgICAgICAgNzgsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjU1LFxuICAgICAgICA4MyxcbiAgICAgICAgMTg5LFxuICAgICAgICAxNCxcbiAgICAgICAgMjUsXG4gICAgICAgIDE1MCxcbiAgICAgICAgODcsXG4gICAgICAgIDc0LFxuICAgICAgICAxNTMsXG4gICAgICAgIDIzLFxuICAgICAgICA2NyxcbiAgICAgICAgMjA2LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIzOCxcbiAgICAgICAgODcsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjM4LFxuICAgICAgICAxNDksXG4gICAgICAgIDE3NixcbiAgICAgICAgMTU3LFxuICAgICAgICAxNTYsXG4gICAgICAgIDMyLFxuICAgICAgICAyLFxuICAgICAgICAyMzUsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTM5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDM1LFxuICAgICAgICA2MSxcbiAgICAgICAgMTNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDMxLFxuICBcImFkdlNlY3JldEtleVwiOiBcInd2WHpUTHNYdkRnV1FRdU1LYmsvQmVXNVZlUHRRdjZqazZHMDlkTlZoZnM9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0OTEzMzk2NjQwMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMzRENzg3QzJFMEQ3RDdEOEM5RUEyNzA5NzBBNkY0MUJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI1MjgwNzk1XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIldxMHVJSTRZUmZHM3dzWGZsRGx0LWdcIixcbiAgXCJwaG9uZUlkXCI6IFwiYmQzMTg2MjctZjBjNi00ZDA1LThhMWQtZTM3MWU1NTdmYjMyXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDg1LFxuICAgICAgNjUsXG4gICAgICAxMzIsXG4gICAgICAxNTgsXG4gICAgICAxNTAsXG4gICAgICAyMjMsXG4gICAgICAxODYsXG4gICAgICA2MyxcbiAgICAgIDk3LFxuICAgICAgMTcyLFxuICAgICAgMjE2LFxuICAgICAgMTAzLFxuICAgICAgMTI2LFxuICAgICAgMjM1LFxuICAgICAgMyxcbiAgICAgIDIzLFxuICAgICAgMTU4LFxuICAgICAgMjE2LFxuICAgICAgNzUsXG4gICAgICAyMjRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNDcsXG4gICAgICAxOTAsXG4gICAgICAzNCxcbiAgICAgIDE1MixcbiAgICAgIDEyNSxcbiAgICAgIDI1LFxuICAgICAgMTUyLFxuICAgICAgNzAsXG4gICAgICAyMzksXG4gICAgICAxODMsXG4gICAgICAyNDQsXG4gICAgICAyMDksXG4gICAgICAxNDMsXG4gICAgICA2NSxcbiAgICAgIDIzOCxcbiAgICAgIDEzOCxcbiAgICAgIDE3LFxuICAgICAgMTQ5LFxuICAgICAgMjA0LFxuICAgICAgNlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJQS1k0M0hZM1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTEzMzk2NjQwMjo4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiT2xhZGltZWppXCIsXG4gICAgXCJsaWRcIjogXCI0OTA5MTk0NjAwNDU0OTo4QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ003VDhad0ZFSkhrMXJZR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiREhPdG5SZnQ3eDB6dDRxbEtsQ09sNkhPYlZMSTdqMk43K2F0Z0hIMDhFQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJ5T29qOGJlM2xlQVVGMHJxMWxsS2g5bW5qelF5NnpRK0ZsN2tWeWxpbWM0aEVTVldSLzFzaGlZbUpZM21WMXV0WHg4MG9xa1NFL2Fxc2N4dktyWDBEZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCI1QU53UkFPODlaZHplaUJwWGcvRTY1MGpucVo2SWdXQStldElrZG8wYWkxWmFDYUczS0lHMlAwcCtxdm5qRjJMS1Fzc3ViRk9HTmhIUGdTeXRTc0hBQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ5MTMzOTY2NDAyOjhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDY0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjUyODA3ODksXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBWnVcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFadS5qc29uIjogIntcImtleURhdGFcIjpcIkJFSmRCRlYxbVhyM3lJSFlORXlERkFXYnJqemJ4ekNvemJsMXlwSVZvdHM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQwMjc1OTYyNyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI1MTM0MTU4ODQzXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
