const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "9133966402";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_01_16_09_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICAxODQsXG4gICAgICAgIDY4LFxuICAgICAgICA4MyxcbiAgICAgICAgNzYsXG4gICAgICAgIDYzLFxuICAgICAgICA2MSxcbiAgICAgICAgNzUsXG4gICAgICAgIDk2LFxuICAgICAgICAxMDYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNjcsXG4gICAgICAgIDY1LFxuICAgICAgICA4OSxcbiAgICAgICAgMjIyLFxuICAgICAgICA3NixcbiAgICAgICAgMTg3LFxuICAgICAgICAyMjIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjUxLFxuICAgICAgICAxODAsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNTEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTgwLFxuICAgICAgICA1MCxcbiAgICAgICAgNzYsXG4gICAgICAgIDU3LFxuICAgICAgICAxODEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc3LFxuICAgICAgICAxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTkwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTYzLFxuICAgICAgICAxOTgsXG4gICAgICAgIDkwLFxuICAgICAgICAyMSxcbiAgICAgICAgMjI4LFxuICAgICAgICAwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE1NixcbiAgICAgICAgODEsXG4gICAgICAgIDExNSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxODEsXG4gICAgICAgIDIzLFxuICAgICAgICA3OCxcbiAgICAgICAgMTE0LFxuICAgICAgICA1NCxcbiAgICAgICAgNjgsXG4gICAgICAgIDYsXG4gICAgICAgIDEwMixcbiAgICAgICAgNTYsXG4gICAgICAgIDExLFxuICAgICAgICAzMSxcbiAgICAgICAgMjksXG4gICAgICAgIDIyNixcbiAgICAgICAgODJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTYzLFxuICAgICAgICAyNDgsXG4gICAgICAgIDg5LFxuICAgICAgICA2MixcbiAgICAgICAgMTgxLFxuICAgICAgICAzLFxuICAgICAgICAyNDIsXG4gICAgICAgIDgwLFxuICAgICAgICAxNzYsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTc2LFxuICAgICAgICA3MyxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNjAsXG4gICAgICAgIDUzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDkxLFxuICAgICAgICA0NSxcbiAgICAgICAgMjAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTYsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTA0LFxuICAgICAgICAxLFxuICAgICAgICA0MyxcbiAgICAgICAgNSxcbiAgICAgICAgMTQ0LFxuICAgICAgICA4NSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMTEsXG4gICAgICAgIDg2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM4LFxuICAgICAgICA0OSxcbiAgICAgICAgMjEwLFxuICAgICAgICAxNzIsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMjUzLFxuICAgICAgICAyNDYsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTE0LFxuICAgICAgICA2NSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNixcbiAgICAgICAgNixcbiAgICAgICAgMjU1LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTExLFxuICAgICAgICA5OCxcbiAgICAgICAgMTMwLFxuICAgICAgICA2OCxcbiAgICAgICAgMTgwLFxuICAgICAgICAyNTMsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTYxLFxuICAgICAgICAzMSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDM1LFxuICAgICAgICA0NSxcbiAgICAgICAgNjcsXG4gICAgICAgIDE3LFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDEzOCxcbiAgICAgICAgOTYsXG4gICAgICAgIDk5LFxuICAgICAgICAxODksXG4gICAgICAgIDEsXG4gICAgICAgIDk0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxNTIsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTI0LFxuICAgICAgICA5MixcbiAgICAgICAgMjE3LFxuICAgICAgICAzMyxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMjUsXG4gICAgICAgIDI0LFxuICAgICAgICA4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxMjIsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE4LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTA4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjYsXG4gICAgICAgIDgwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI3LFxuICAgICAgICAxOTksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMixcbiAgICAgICAgMjI5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDUxLFxuICAgICAgICAyMDcsXG4gICAgICAgIDUzLFxuICAgICAgICAyMjYsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTI5LFxuICAgICAgICAxNzQsXG4gICAgICAgIDYwLFxuICAgICAgICAxNTAsXG4gICAgICAgIDQwLFxuICAgICAgICA3MyxcbiAgICAgICAgMjA2LFxuICAgICAgICAyNDcsXG4gICAgICAgIDYzLFxuICAgICAgICAxLFxuICAgICAgICAyMDMsXG4gICAgICAgIDM5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQwLFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMSxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA3MixcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxMDhcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAyNixcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDEyMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMixcbiAgICAgICAgMzAsXG4gICAgICAgIDUwLFxuICAgICAgICA5MyxcbiAgICAgICAgOTEsXG4gICAgICAgIDIxOSxcbiAgICAgICAgOCxcbiAgICAgICAgODYsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMjksXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTMxLFxuICAgICAgICAxNTMsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjMyLFxuICAgICAgICA3MixcbiAgICAgICAgMjAyLFxuICAgICAgICA3OCxcbiAgICAgICAgMTQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMzksXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxODQsXG4gICAgICAgIDg0LFxuICAgICAgICAyNDcsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNzcsXG4gICAgICAgIDUsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTc5LFxuICAgICAgICAyMTQsXG4gICAgICAgIDQ0LFxuICAgICAgICAzMSxcbiAgICAgICAgMTIyLFxuICAgICAgICA4MSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxOTQsXG4gICAgICAgIDIxMyxcbiAgICAgICAgNzAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTUxLFxuICAgICAgICAyNixcbiAgICAgICAgNyxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxNjMsXG4gICAgICAgIDE3LFxuICAgICAgICAyMjksXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNDEsXG4gICAgICAgIDI4LFxuICAgICAgICAxNjcsXG4gICAgICAgIDExNyxcbiAgICAgICAgNjQsXG4gICAgICAgIDQ3LFxuICAgICAgICA2NSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNDMsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTM3XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA2MSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJYZjdsc2VmbWdPVldJRTMzZFJWMzlsSWRVZ3BCeitxZlh1ME9GeEdnbXNJPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkxMzM5NjY0MDJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkM1QkEyRkVFRTlEQTM2MDAzNTZGN0M2REU4NjZFMEQ4XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTE1MzM4OVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkxMzM5NjY0MDJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjU4QTJBODk4NzdBQTI0RUYzRUNDRTQyNjczRDA0MzUxXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTE1MzM5MFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJwdEd0OVhtLVMxT3lLWDJWdWRhLW53XCIsXG4gIFwicGhvbmVJZFwiOiBcIjdkYTgzZDA1LTkyZGMtNDNmMS05OTRlLWEzYTU0MzRhZTI0ZlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxODMsXG4gICAgICAxMTEsXG4gICAgICAxNjMsXG4gICAgICAyMCxcbiAgICAgIDUyLFxuICAgICAgMTk1LFxuICAgICAgOSxcbiAgICAgIDI0NSxcbiAgICAgIDEwMyxcbiAgICAgIDI0NixcbiAgICAgIDE1NixcbiAgICAgIDI0MyxcbiAgICAgIDE4MCxcbiAgICAgIDgyLFxuICAgICAgMjAzLFxuICAgICAgMzIsXG4gICAgICA4MixcbiAgICAgIDExMCxcbiAgICAgIDE1NyxcbiAgICAgIDI0NFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA5OCxcbiAgICAgIDIzNSxcbiAgICAgIDExMyxcbiAgICAgIDE0MyxcbiAgICAgIDE4NixcbiAgICAgIDExMSxcbiAgICAgIDE3OSxcbiAgICAgIDY4LFxuICAgICAgNzksXG4gICAgICAyNTEsXG4gICAgICAxMDcsXG4gICAgICA0NixcbiAgICAgIDgwLFxuICAgICAgMjM0LFxuICAgICAgMjEsXG4gICAgICAxODQsXG4gICAgICAxMzUsXG4gICAgICAyMDksXG4gICAgICA4MCxcbiAgICAgIDI1MlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJCVzI4R0o2RlwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTEzMzk2NjQwMjo2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiT2xhZGltZWppXCIsXG4gICAgXCJsaWRcIjogXCI0OTA5MTk0NjAwNDU0OTo2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ016VDhad0ZFT2VBejdZR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiREhPdG5SZnQ3eDB6dDRxbEtsQ09sNkhPYlZMSTdqMk43K2F0Z0hIMDhFQT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJHTE84eXpTT2hkd0pyVm5KQjVNTW1oWGFTVUZ3clVJQmRlUE4vbXYzY0V4VmFkbUJUaEMzR2o3d3I3L3h3S3JSamZYWlM5QmFvcTFFRHMybU1jMnRBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJIWVNHa01kRkJoQmR1TWhoSE9WMmZLQ3N5RHFIQXBkWHhMRHFvYS83bEgvTitKOHpkNFBPOHZPMlAxdXhhMC9GTG9jZ0YwcjBQVUQvRjNCYmR0RHZpZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ5MTMzOTY2NDAyOjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDY0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjUxNTMzODcsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBWndcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFady5qc29uIjogIntcImtleURhdGFcIjpcIjdtZUl3ekxGSGorWE1YZzcrbEhhYWp0cWh1SEFtRUUxQWhGZWRuaVp1dVE9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQwMjc1OTYyOCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI1MTUzMzg4NzE0XCJ9Igp9,  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
